version: '3.8'

services:
  expo:
    container_name: expo
    build: .
    volumes:
      - ./:/usr/src/app
    environment:
      - REACT_NATIVE_PACKAGER_HOSTNAME=${LOCAL_IP_ADDR}
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    tty: true

